CREATE TABLE `balances_int` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`address` VARCHAR(100) NOT NULL,
	`amount` VARCHAR(100) NOT NULL,
	`creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
COLLATE='utf8_general_ci';
ENGINE=InnoDB;